---

- hosts: all
  become: yes
  tasks:

  - name: update repository
    apt:
      update_cache: yes
      

  - name: remove apache
    apt:
      name: apache
      state: absent


  - name: remove php
    apt:
      name: libapache2-mod-php
      state: absent


  - name: remove httpd
    apt:
      name: httpd
      state: absent
